// generated by gen_vectors.py
#include "vectors.h"

void byte_vector_allocate(byte_vector* vec) {
  vec->data = ALLOCATE(byte, 8);
  vec->count = 0;
  vec->cap = 8;
}
void byte_vector_deallocate(byte_vector* vec) {
  FREE(vec->data);
  vec->count = 0;
  vec->cap = 0;
}
void byte_reset(byte_vector* vec) {
  vec->count = 0;
}
void byte_vector_pushback(byte_vector* vec, byte val) {
  if(vec->cap < vec->count +1) {
    vec->cap *= 2;
    vec->data = REALLOCATE(byte, vec->data, vec->cap);
  }
  vec->data[vec->count] = val;
  vec->count += 1;
}
byte byte_vector_pop(byte_vector* vec) {
  if(vec->count == 0) {
    fprintf(stderr, "Pop on an empty vector(byte). Aborting\n");
    exit(1);
  }
  vec->count -= 1;
  return vec->data[vec->count];
}

void value_vector_allocate(value_vector* vec) {
  vec->data = ALLOCATE(value, 8);
  vec->count = 0;
  vec->cap = 8;
}
void value_vector_deallocate(value_vector* vec) {
  FREE(vec->data);
  vec->count = 0;
  vec->cap = 0;
}
void value_reset(value_vector* vec) {
  vec->count = 0;
}
void value_vector_pushback(value_vector* vec, value val) {
  if(vec->cap < vec->count +1) {
    vec->cap *= 2;
    vec->data = REALLOCATE(value, vec->data, vec->cap);
  }
  vec->data[vec->count] = val;
  vec->count += 1;
}
value value_vector_pop(value_vector* vec) {
  if(vec->count == 0) {
    fprintf(stderr, "Pop on an empty vector(value). Aborting\n");
    exit(1);
  }
  vec->count -= 1;
  return vec->data[vec->count];
}
