// generated by gen_vectors.py
#pragma once
#include "value.h"

typedef struct {
byte* data;
i32 count, cap;
} byte_vector;
void byte_vector_allocate(byte_vector* vec);
void byte_vector_pushback(byte_vector* vec, byte val);
void byte_vector_deallocate(byte_vector* vec);
byte byte_vector_pop(byte_vector* vec);
void byte_reset(byte_vector* vec);

typedef struct {
value* data;
i32 count, cap;
} value_vector;
void value_vector_allocate(value_vector* vec);
void value_vector_pushback(value_vector* vec, value val);
void value_vector_deallocate(value_vector* vec);
value value_vector_pop(value_vector* vec);
void value_reset(value_vector* vec);
